apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exam-resource-reader-binding
  namespace: exam
subjects:
- kind: User 
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: exam-resource-reader
  apiGroup: rbac.authorization.k8s.io
